export function generateSqlInsert(table: string, data: Array<{ id: string; name: string; [key: string]: any }>): string {
  if (!data || !data.length) return '-- Tidak ada data untuk di-generate';

  const rows = data.map(item => {
    const safeName = item.name.replace(/'/g, "''");
    const parentKey = Object.keys(item).find(k => k.endsWith('_id'));
    const parentId = parentKey ? item[parentKey] : null;
    return parentId 
      ? `  ('${item.id}', '${parentId}', '${safeName}')` 
      : `  ('${item.id}', '${safeName}')`;
  });

  const columns = table === 'provinces' ? '(id, name)' : `(id, parent_id, name)`;
  return `-- SQL INSERT DUMP: ${table.toUpperCase()}
-- Generated by Nusantara Region Explorer (https://spixelsdev.github.io/nusantara-region-explorer/)
-- Total Rows: ${data.length}

INSERT INTO \`${table}\` ${columns} VALUES
${rows.join(',\n')};`;
}

export function generatePrismaSeedSnippet(table: string, data: Array<{ id: string; name: string; [key: string]: any }>): string {
  if (!data || !data.length) return '// Tidak ada data';

  const previewData = JSON.stringify(data.slice(0, 4), null, 2);
  const modelName = table === 'provinces' ? 'province' : table === 'regencies' ? 'regency' : table === 'districts' ? 'district' : 'village';

  return `// prisma/seed.ts
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding ${table} (${data.length} records)...');

  // Preview data payload (menampilkan sampel data)
  const data = ${previewData};

  await prisma.${modelName}.createMany({
    data,
    skipDuplicates: true,
  });

  console.log('Seeding ${table} selesai!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });`;
}

export function generateReactComponentSnippet(): string {
  return `import React, { useState, useEffect } from 'react';

const BASE_URL = 'https://www.emsifa.com/api-wilayah-indonesia/api';

export default function IndonesiaRegionSelector({ onSelect }) {
  const [provinces, setProvinces] = useState([]);
  const [regencies, setRegencies] = useState([]);
  const [districts, setDistricts] = useState([]);
  const [villages, setVillages] = useState([]);

  const [selectedProv, setSelectedProv] = useState('');
  const [selectedReg, setSelectedReg] = useState('');
  const [selectedDist, setSelectedDist] = useState('');
  const [selectedVil, setSelectedVil] = useState('');

  // Load provinces on mount
  useEffect(() => {
    fetch(\`\${BASE_URL}/provinces.json\`)
      .then(res => res.json())
      .then(setProvinces);
  }, []);

  const handleProvinceChange = async (e) => {
    const provId = e.target.value;
    setSelectedProv(provId);
    setSelectedReg('');
    setSelectedDist('');
    setSelectedVil('');
    setRegencies([]);
    setDistricts([]);
    setVillages([]);
    if (provId) {
      const res = await fetch(\`\${BASE_URL}/regencies/\${provId}.json\`);
      setRegencies(await res.json());
    }
  };

  const handleRegencyChange = async (e) => {
    const regId = e.target.value;
    setSelectedReg(regId);
    setSelectedDist('');
    setSelectedVil('');
    setDistricts([]);
    setVillages([]);
    if (regId) {
      const res = await fetch(\`\${BASE_URL}/districts/\${regId}.json\`);
      setDistricts(await res.json());
    }
  };

  const handleDistrictChange = async (e) => {
    const distId = e.target.value;
    setSelectedDist(distId);
    setSelectedVil('');
    setVillages([]);
    if (distId) {
      const res = await fetch(\`\${BASE_URL}/villages/\${distId}.json\`);
      setVillages(await res.json());
    }
  };

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 font-sans">
      <div>
        <label className="block text-xs font-semibold mb-1 text-slate-700">Provinsi</label>
        <select 
          value={selectedProv} 
          onChange={handleProvinceChange}
          className="w-full border border-slate-300 rounded px-2.5 py-1.5 text-xs bg-white focus:ring-1 focus:ring-sky-500"
        >
          <option value="">-- Pilih Provinsi --</option>
          {provinces.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
        </select>
      </div>

      <div>
        <label className="block text-xs font-semibold mb-1 text-slate-700">Kabupaten / Kota</label>
        <select 
          value={selectedReg} 
          onChange={handleRegencyChange} 
          disabled={!selectedProv}
          className="w-full border border-slate-300 rounded px-2.5 py-1.5 text-xs bg-white disabled:bg-slate-100 focus:ring-1 focus:ring-sky-500"
        >
          <option value="">-- Pilih Kab/Kota --</option>
          {regencies.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}
        </select>
      </div>

      <div>
        <label className="block text-xs font-semibold mb-1 text-slate-700">Kecamatan</label>
        <select 
          value={selectedDist} 
          onChange={handleDistrictChange} 
          disabled={!selectedReg}
          className="w-full border border-slate-300 rounded px-2.5 py-1.5 text-xs bg-white disabled:bg-slate-100 focus:ring-1 focus:ring-sky-500"
        >
          <option value="">-- Pilih Kecamatan --</option>
          {districts.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}
        </select>
      </div>

      <div>
        <label className="block text-xs font-semibold mb-1 text-slate-700">Kelurahan / Desa</label>
        <select 
          value={selectedVil} 
          onChange={e => setSelectedVil(e.target.value)} 
          disabled={!selectedDist}
          className="w-full border border-slate-300 rounded px-2.5 py-1.5 text-xs bg-white disabled:bg-slate-100 focus:ring-1 focus:ring-sky-500"
        >
          <option value="">-- Pilih Kelurahan/Desa --</option>
          {villages.map(v => <option key={v.id} value={v.id}>{v.name}</option>)}
        </select>
      </div>
    </div>
  );
}`;
}

export function generateVueComponentSnippet(): string {
  return `<script setup lang="ts">
import { ref, onMounted } from 'vue';

interface RegionItem { id: string; name: string; }

const BASE_URL = 'https://www.emsifa.com/api-wilayah-indonesia/api';

const provinces = ref<RegionItem[]>([]);
const regencies = ref<RegionItem[]>([]);
const districts = ref<RegionItem[]>([]);
const villages = ref<RegionItem[]>([]);

const selectedProv = ref('');
const selectedReg = ref('');
const selectedDist = ref('');
const selectedVil = ref('');

onMounted(async () => {
  const res = await fetch(\`\${BASE_URL}/provinces.json\`);
  provinces.value = await res.json();
});

const onProvinceChange = async () => {
  selectedReg.value = '';
  selectedDist.value = '';
  selectedVil.value = '';
  regencies.value = [];
  districts.value = [];
  villages.value = [];
  if (selectedProv.value) {
    const res = await fetch(\`\${BASE_URL}/regencies/\${selectedProv.value}.json\`);
    regencies.value = await res.json();
  }
};

const onRegencyChange = async () => {
  selectedDist.value = '';
  selectedVil.value = '';
  districts.value = [];
  villages.value = [];
  if (selectedReg.value) {
    const res = await fetch(\`\${BASE_URL}/districts/\${selectedReg.value}.json\`);
    districts.value = await res.json();
  }
};

const onDistrictChange = async () => {
  selectedVil.value = '';
  villages.value = [];
  if (selectedDist.value) {
    const res = await fetch(\`\${BASE_URL}/villages/\${selectedDist.value}.json\`);
    villages.value = await res.json();
  }
};
</script>

<template>
  <div class="grid grid-cols-1 sm:grid-cols-2 gap-3 font-sans">
    <div>
      <label class="block text-xs font-semibold mb-1 text-slate-700 dark:text-slate-300">Provinsi</label>
      <select v-model="selectedProv" @change="onProvinceChange" class="w-full border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs rounded px-2.5 py-1.5">
        <option value="">-- Pilih Provinsi --</option>
        <option v-for="p in provinces" :key="p.id" :value="p.id">{{ p.name }}</option>
      </select>
    </div>

    <div>
      <label class="block text-xs font-semibold mb-1 text-slate-700 dark:text-slate-300">Kabupaten / Kota</label>
      <select v-model="selectedReg" @change="onRegencyChange" :disabled="!selectedProv" class="w-full border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 disabled:opacity-50 text-xs rounded px-2.5 py-1.5">
        <option value="">-- Pilih Kab/Kota --</option>
        <option v-for="r in regencies" :key="r.id" :value="r.id">{{ r.name }}</option>
      </select>
    </div>

    <div>
      <label class="block text-xs font-semibold mb-1 text-slate-700 dark:text-slate-300">Kecamatan</label>
      <select v-model="selectedDist" @change="onDistrictChange" :disabled="!selectedReg" class="w-full border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 disabled:opacity-50 text-xs rounded px-2.5 py-1.5">
        <option value="">-- Pilih Kecamatan --</option>
        <option v-for="d in districts" :key="d.id" :value="d.id">{{ d.name }}</option>
      </select>
    </div>

    <div>
      <label class="block text-xs font-semibold mb-1 text-slate-700 dark:text-slate-300">Kelurahan / Desa</label>
      <select v-model="selectedVil" :disabled="!selectedDist" class="w-full border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 disabled:opacity-50 text-xs rounded px-2.5 py-1.5">
        <option value="">-- Pilih Kelurahan/Desa --</option>
        <option v-for="v in villages" :key="v.id" :value="v.id">{{ v.name }}</option>
      </select>
    </div>
  </div>
</template>`;
}

export function generateVanillaHtmlSnippet(): string {
  return `<!-- HTML + Vanilla JavaScript Cascading Dropdown -->
<div style="display:grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 12px; font-family: sans-serif; font-size: 13px;">
  <div>
    <label>Provinsi</label>
    <select id="select-prov" style="width:100%; padding: 6px; border:1px solid #ccc; border-radius:4px;">
      <option value="">-- Pilih Provinsi --</option>
    </select>
  </div>
  <div>
    <label>Kabupaten/Kota</label>
    <select id="select-reg" disabled style="width:100%; padding: 6px; border:1px solid #ccc; border-radius:4px;">
      <option value="">-- Pilih Kab/Kota --</option>
    </select>
  </div>
  <div>
    <label>Kecamatan</label>
    <select id="select-dist" disabled style="width:100%; padding: 6px; border:1px solid #ccc; border-radius:4px;">
      <option value="">-- Pilih Kecamatan --</option>
    </select>
  </div>
  <div>
    <label>Kelurahan/Desa</label>
    <select id="select-vil" disabled style="width:100%; padding: 6px; border:1px solid #ccc; border-radius:4px;">
      <option value="">-- Pilih Kelurahan/Desa --</option>
    </select>
  </div>
</div>

<script>
  const API_BASE = 'https://www.emsifa.com/api-wilayah-indonesia/api';
  const $prov = document.getElementById('select-prov');
  const $reg = document.getElementById('select-reg');
  const $dist = document.getElementById('select-dist');
  const $vil = document.getElementById('select-vil');

  fetch(\`\${API_BASE}/provinces.json\`)
    .then(r => r.json())
    .then(data => {
      data.forEach(p => $prov.add(new Option(p.name, p.id)));
    });

  $prov.addEventListener('change', () => {
    $reg.innerHTML = '<option value="">-- Pilih Kab/Kota --</option>';
    $dist.innerHTML = '<option value="">-- Pilih Kecamatan --</option>';
    $vil.innerHTML = '<option value="">-- Pilih Kelurahan/Desa --</option>';
    $reg.disabled = !$prov.value;
    $dist.disabled = true;
    $vil.disabled = true;
    if ($prov.value) {
      fetch(\`\${API_BASE}/regencies/\${$prov.value}.json\`)
        .then(r => r.json())
        .then(data => data.forEach(item => $reg.add(new Option(item.name, item.id))));
    }
  });

  $reg.addEventListener('change', () => {
    $dist.innerHTML = '<option value="">-- Pilih Kecamatan --</option>';
    $vil.innerHTML = '<option value="">-- Pilih Kelurahan/Desa --</option>';
    $dist.disabled = !$reg.value;
    $vil.disabled = true;
    if ($reg.value) {
      fetch(\`\${API_BASE}/districts/\${$reg.value}.json\`)
        .then(r => r.json())
        .then(data => data.forEach(item => $dist.add(new Option(item.name, item.id))));
    }
  });

  $dist.addEventListener('change', () => {
    $vil.innerHTML = '<option value="">-- Pilih Kelurahan/Desa --</option>';
    $vil.disabled = !$dist.value;
    if ($dist.value) {
      fetch(\`\${API_BASE}/villages/\${$dist.value}.json\`)
        .then(r => r.json())
        .then(data => data.forEach(item => $vil.add(new Option(item.name, item.id))));
    }
  });
</script>`;
}

export function downloadSqlFile(filename: string, sqlContent: string) {
  const blob = new Blob([sqlContent], { type: 'application/sql;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
